---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-nginx-cm
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <body>

    <h1>Ompragash love's</h1>
    <p>Open Source <3</p>

    </body>
    </html>
    
---
apiVersion: v1
kind: Service
metadata:
  name: sample-nginx-service
spec:
  ports:
  - port: 80
  selector:
    app: sample-nginx
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nginx
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx-container
        image: nginx:1.16.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-volume
          mountPath: "/usr/share/nginx/html/index.html"
          subPath: index.html
      volumes:
          - name: index-volume
            configMap:
              name: sample-nginx-cm
